version: '3.2'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: [USE ENV]
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: [USE ENV]
    volumes:
      - source: ./mariadb
        type: bind
        target: /var/lib/mysql
  fpm:
    image: nextcloud:fpm
    # exposed port: 9000
    restart: always
    volumes:
      - source: src
        type: volume
        target: /var/www/html
      - source: ./data
        type: bind
        target: /var/www/html/data
      - source: ./config
        type: bind
        target: /var/www/html/config/
    depends_on:
      - db
  web:
    image: nginx:1.15
    restart: always
    volumes:
      - source: src
        type: volume
        target: /var/www/html
        read_only: yes
      - source: ./nginx.conf
        type: bind
        target: /etc/nginx/conf.d/default.conf
        read_only: yes
    networks:
      - nextcloud
      - default
    depends_on:
      - fpm
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host:next.localdomain"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_nextcloud"

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - source: redis
        type: volume
        target: /data

networks:
  nextcloud:
    external:
      name: traefik_nextcloud

volumes:
  src: {}
  redis: {}
