global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-host'

rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['reverse-proxy:8080']

# End point not available in 2.6.2 release (20180910)
# ###################################################
#  - job_name: 'registry'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['registry:5001']
